from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_ativar(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(712, 597)
        Cadastro.setStyleSheet("background-color: rgb(0, 70, 112);")
        self.label = QtWidgets.QLabel(Cadastro)
        self.label.setGeometry(QtCore.QRect(240, 60, 241, 21))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Cadastro)
        self.tableWidget.setGeometry(QtCore.QRect(40, 140, 631, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.excluir_tarefa_Button_3 = QtWidgets.QPushButton(Cadastro)
        self.excluir_tarefa_Button_3.setGeometry(QtCore.QRect(370, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.excluir_tarefa_Button_3.setFont(font)
        self.excluir_tarefa_Button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.excluir_tarefa_Button_3.setStyleSheet("QPushButton{ color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border-radius: 10px; } QPushButton:hover{ color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); }")
        self.excluir_tarefa_Button_3.setObjectName("excluir_tarefa_Button_3")
        self.excluir_tarefa_Button = QtWidgets.QPushButton(Cadastro)
        self.excluir_tarefa_Button.setGeometry(QtCore.QRect(220, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.excluir_tarefa_Button.setFont(font)
        self.excluir_tarefa_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.excluir_tarefa_Button.setStyleSheet("QPushButton{ color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border-radius: 10px; } QPushButton:hover{ color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); }")
        self.excluir_tarefa_Button.setObjectName("excluir_tarefa_Button")
        self.excluir_tarefa_Button_2 = QtWidgets.QPushButton(Cadastro)
        self.excluir_tarefa_Button_2.setGeometry(QtCore.QRect(600, 560, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.excluir_tarefa_Button_2.setFont(font)
        self.excluir_tarefa_Button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.excluir_tarefa_Button_2.setStyleSheet("QPushButton{ color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border-radius: 10px; } QPushButton:hover{ color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); }")
        self.excluir_tarefa_Button_2.setObjectName("excluir_tarefa_Button_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(Cadastro)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 140, 631, 381))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "Form"))
        self.label.setText(_translate("Cadastro", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Tasks</span></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Cadastro", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cadastro", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cadastro", "Titulo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cadastro", "Descricao"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Cadastro", "Prazo"))
        self.excluir_tarefa_Button_3.setText(_translate("Cadastro", "Excluir"))
        self.excluir_tarefa_Button.setText(_translate("Cadastro", "Ativar"))
        self.excluir_tarefa_Button_2.setText(_translate("Cadastro", "Voltar"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Cadastro", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Cadastro", "Titulo"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Cadastro", "Descricao"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Cadastro", "Prazo"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QWidget()
    ui = Tela_ativar()
    ui.setupUi(Cadastro)
    Cadastro.show()
    sys.exit(app.exec_())